'area: ci':
  - changed-files:
      - any-glob-to-any-file:
          - .github/CODEOWNERS
          - .github/dependabot.yml
          - .github/workflows/**

'area: docs':
  - changed-files:
      - any-glob-to-any-file:
          - .github/CONTRIBUTING.md
          - README.md
          - docs/**

'area: ui':
  - changed-files:
      - any-glob-to-any-file:
          - ui/**

'area: e2e':
  - changed-files:
      - any-glob-to-any-file:
          - e2e/**
          - playwright.config.ts

'area: tauri':
  - changed-files:
      - any-glob-to-any-file:
          - koharu/**

'area: app':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-app/**

'area: core':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-core/**
          - koharu-runtime/**

'area: rpc':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-rpc/**
          - ui/lib/api/**
          - ui/openapi.json
          - ui/orval.config.ts

'area: llm':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-llm/**

'area: ml':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-ml/**
          - models/**

'area: renderer':
  - changed-files:
      - any-glob-to-any-file:
          - koharu-psd/**
          - koharu-renderer/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/Cargo.toml'
          - Cargo.lock
          - '**/package.json'
          - bun.lock
