/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ApiError,
  DocumentDetail,
  DocumentSummary,
  GetDocumentThumbnailParams,
  ImportDocumentsBody,
  ImportDocumentsParams,
  ImportResult,
  ReorderRequest,
  UpdateDocumentStyleRequest,
} from '../schemas'

import { fetchApi } from '.././fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getListDocumentsUrl = () => {
  return `/api/v1/documents`
}

export const listDocuments = async (
  options?: RequestInit,
): Promise<DocumentSummary[]> => {
  return fetchApi<DocumentSummary[]>(getListDocumentsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getListDocumentsQueryKey = () => {
  return [`/api/v1/documents`] as const
}

export const getListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
  >
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListDocumentsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({
    signal,
  }) => listDocuments({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDocuments>>
>
export type ListDocumentsQueryError = ApiError

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListDocumentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getImportDocumentsUrl = (params?: ImportDocumentsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/documents?${stringifiedParams}`
    : `/api/v1/documents`
}

export const importDocuments = async (
  importDocumentsBody: ImportDocumentsBody,
  params?: ImportDocumentsParams,
  options?: RequestInit,
): Promise<ImportResult> => {
  const formData = new FormData()
  importDocumentsBody.files.forEach((value) => formData.append(`files`, value))

  return fetchApi<ImportResult>(getImportDocumentsUrl(params), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getImportDocumentsMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importDocuments>>,
    TError,
    { data: ImportDocumentsBody; params?: ImportDocumentsParams },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof importDocuments>>,
  TError,
  { data: ImportDocumentsBody; params?: ImportDocumentsParams },
  TContext
> => {
  const mutationKey = ['importDocuments']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importDocuments>>,
    { data: ImportDocumentsBody; params?: ImportDocumentsParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return importDocuments(data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ImportDocumentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof importDocuments>>
>
export type ImportDocumentsMutationBody = ImportDocumentsBody
export type ImportDocumentsMutationError = ApiError

export const useImportDocuments = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof importDocuments>>,
      TError,
      { data: ImportDocumentsBody; params?: ImportDocumentsParams },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof importDocuments>>,
  TError,
  { data: ImportDocumentsBody; params?: ImportDocumentsParams },
  TContext
> => {
  return useMutation(getImportDocumentsMutationOptions(options), queryClient)
}

export const getReorderDocumentsUrl = () => {
  return `/api/v1/documents/order`
}

export const reorderDocuments = async (
  reorderRequest: ReorderRequest,
  options?: RequestInit,
): Promise<DocumentSummary[]> => {
  return fetchApi<DocumentSummary[]>(getReorderDocumentsUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reorderRequest),
  })
}

export const getReorderDocumentsMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reorderDocuments>>,
    TError,
    { data: ReorderRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof reorderDocuments>>,
  TError,
  { data: ReorderRequest },
  TContext
> => {
  const mutationKey = ['reorderDocuments']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reorderDocuments>>,
    { data: ReorderRequest }
  > = (props) => {
    const { data } = props ?? {}

    return reorderDocuments(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReorderDocumentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof reorderDocuments>>
>
export type ReorderDocumentsMutationBody = ReorderRequest
export type ReorderDocumentsMutationError = ApiError

export const useReorderDocuments = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reorderDocuments>>,
      TError,
      { data: ReorderRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reorderDocuments>>,
  TError,
  { data: ReorderRequest },
  TContext
> => {
  return useMutation(getReorderDocumentsMutationOptions(options), queryClient)
}

export const getGetDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}`
}

export const getDocument = async (
  documentId: string,
  options?: RequestInit,
): Promise<DocumentDetail> => {
  return fetchApi<DocumentDetail>(getGetDocumentUrl(documentId), {
    ...options,
    method: 'GET',
  })
}

export const getGetDocumentQueryKey = (documentId: string) => {
  return [`/api/v1/documents/${documentId}`] as const
}

export const getGetDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = ApiError,
>(
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDocumentQueryKey(documentId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({
    signal,
  }) => getDocument(documentId, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!documentId,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocument>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocument>>
>
export type GetDocumentQueryError = ApiError

export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = ApiError,
>(
  documentId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = ApiError,
>(
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = ApiError,
>(
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = ApiError,
>(
  documentId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetDocumentQueryOptions(documentId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getUpdateDocumentStyleUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/style`
}

export const updateDocumentStyle = async (
  documentId: string,
  updateDocumentStyleRequest: UpdateDocumentStyleRequest,
  options?: RequestInit,
): Promise<UpdateDocumentStyleRequest> => {
  return fetchApi<UpdateDocumentStyleRequest>(
    getUpdateDocumentStyleUrl(documentId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateDocumentStyleRequest),
    },
  )
}

export const getUpdateDocumentStyleMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDocumentStyle>>,
    TError,
    { documentId: string; data: UpdateDocumentStyleRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDocumentStyle>>,
  TError,
  { documentId: string; data: UpdateDocumentStyleRequest },
  TContext
> => {
  const mutationKey = ['updateDocumentStyle']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDocumentStyle>>,
    { documentId: string; data: UpdateDocumentStyleRequest }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return updateDocumentStyle(documentId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateDocumentStyleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDocumentStyle>>
>
export type UpdateDocumentStyleMutationBody = UpdateDocumentStyleRequest
export type UpdateDocumentStyleMutationError = ApiError

export const useUpdateDocumentStyle = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDocumentStyle>>,
      TError,
      { documentId: string; data: UpdateDocumentStyleRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDocumentStyle>>,
  TError,
  { documentId: string; data: UpdateDocumentStyleRequest },
  TContext
> => {
  return useMutation(
    getUpdateDocumentStyleMutationOptions(options),
    queryClient,
  )
}
export const getGetDocumentThumbnailUrl = (
  documentId: string,
  params?: GetDocumentThumbnailParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/documents/${documentId}/thumbnail?${stringifiedParams}`
    : `/api/v1/documents/${documentId}/thumbnail`
}

export const getDocumentThumbnail = async (
  documentId: string,
  params?: GetDocumentThumbnailParams,
  options?: RequestInit,
): Promise<Blob> => {
  return fetchApi<Blob>(getGetDocumentThumbnailUrl(documentId, params), {
    ...options,
    method: 'GET',
  })
}

export const getGetDocumentThumbnailQueryKey = (
  documentId: string,
  params?: GetDocumentThumbnailParams,
) => {
  return [
    `/api/v1/documents/${documentId}/thumbnail`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetDocumentThumbnailQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocumentThumbnail>>,
  TError = ApiError,
>(
  documentId: string,
  params?: GetDocumentThumbnailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentThumbnail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetDocumentThumbnailQueryKey(documentId, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDocumentThumbnail>>
  > = ({ signal }) =>
    getDocumentThumbnail(documentId, params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!documentId,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocumentThumbnail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentThumbnailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocumentThumbnail>>
>
export type GetDocumentThumbnailQueryError = ApiError

export function useGetDocumentThumbnail<
  TData = Awaited<ReturnType<typeof getDocumentThumbnail>>,
  TError = ApiError,
>(
  documentId: string,
  params: undefined | GetDocumentThumbnailParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getDocumentThumbnail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocumentThumbnail<
  TData = Awaited<ReturnType<typeof getDocumentThumbnail>>,
  TError = ApiError,
>(
  documentId: string,
  params?: GetDocumentThumbnailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentThumbnail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getDocumentThumbnail>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocumentThumbnail<
  TData = Awaited<ReturnType<typeof getDocumentThumbnail>>,
  TError = ApiError,
>(
  documentId: string,
  params?: GetDocumentThumbnailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentThumbnail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetDocumentThumbnail<
  TData = Awaited<ReturnType<typeof getDocumentThumbnail>>,
  TError = ApiError,
>(
  documentId: string,
  params?: GetDocumentThumbnailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentThumbnail>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetDocumentThumbnailQueryOptions(
    documentId,
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
