[package]
name = "koharu-config"
version.workspace = true
edition.workspace = true
description = "Extensible typed configuration storage for Koharu."
license.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
atomicwrites = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
