/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type { ApiError, ExportBatchRequest, ExportDocumentParams, ExportResult } from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getExportDocumentUrl = (
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/documents/${documentId}/export/${format}?${stringifiedParams}`
    : `/api/v1/documents/${documentId}/export/${format}`
}

export const exportDocument = async (
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
  options?: RequestInit,
): Promise<Blob> => {
  return fetchApi<Blob>(getExportDocumentUrl(documentId, format, params), {
    ...options,
    method: 'GET',
  })
}

export const getExportDocumentQueryKey = (
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
) => {
  return [`/api/v1/documents/${documentId}/export/${format}`, ...(params ? [params] : [])] as const
}

export const getExportDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof exportDocument>>,
  TError = ApiError,
>(
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getExportDocumentQueryKey(documentId, format, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof exportDocument>>> = ({ signal }) =>
    exportDocument(documentId, format, params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!(documentId && format),
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type ExportDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof exportDocument>>>
export type ExportDocumentQueryError = ApiError

export function useExportDocument<
  TData = Awaited<ReturnType<typeof exportDocument>>,
  TError = ApiError,
>(
  documentId: string,
  format: string,
  params: undefined | ExportDocumentParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportDocument>>,
          TError,
          Awaited<ReturnType<typeof exportDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportDocument<
  TData = Awaited<ReturnType<typeof exportDocument>>,
  TError = ApiError,
>(
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportDocument>>,
          TError,
          Awaited<ReturnType<typeof exportDocument>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportDocument<
  TData = Awaited<ReturnType<typeof exportDocument>>,
  TError = ApiError,
>(
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useExportDocument<
  TData = Awaited<ReturnType<typeof exportDocument>>,
  TError = ApiError,
>(
  documentId: string,
  format: string,
  params?: ExportDocumentParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof exportDocument>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getExportDocumentQueryOptions(documentId, format, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getBatchExportUrl = () => {
  return `/api/v1/exports`
}

export const batchExport = async (
  exportBatchRequest: ExportBatchRequest,
  options?: RequestInit,
): Promise<ExportResult> => {
  return fetchApi<ExportResult>(getBatchExportUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exportBatchRequest),
  })
}

export const getBatchExportMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchExport>>,
    TError,
    { data: ExportBatchRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchExport>>,
  TError,
  { data: ExportBatchRequest },
  TContext
> => {
  const mutationKey = ['batchExport']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchExport>>,
    { data: ExportBatchRequest }
  > = (props) => {
    const { data } = props ?? {}

    return batchExport(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type BatchExportMutationResult = NonNullable<Awaited<ReturnType<typeof batchExport>>>
export type BatchExportMutationBody = ExportBatchRequest
export type BatchExportMutationError = ApiError

export const useBatchExport = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchExport>>,
      TError,
      { data: ExportBatchRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchExport>>,
  TError,
  { data: ExportBatchRequest },
  TContext
> => {
  return useMutation(getBatchExportMutationOptions(options), queryClient)
}
