blank_issues_enabled: false

contact_links:
  - name: Ask a question or get support
    url: https://discord.gg/mHvHkxGnUY
    about: Use Discord for support, questions, and help deciding where to report something.
