use std::collections::HashSet;

use anyhow::{Context, Result, bail};
use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use syn::{
    Abi, Attribute, Expr, ExprLit, FnArg, ForeignItem, GenericArgument, Item, Lit, LitStr, Meta,
    Pat, PathArguments, Signature, Type, Visibility,
};

struct Function {
    attrs: Vec<Attribute>,
    vis: Visibility,
    sig: Signature,
    abi: Abi,
}

pub fn rewrite_bindings(source: &str, library_name: &str) -> Result<String> {
    rewrite_bindings_for_libraries(source, &[library_name.to_owned()])
}

pub fn rewrite_bindings_for_libraries(source: &str, library_names: &[String]) -> Result<String> {
    if library_names.is_empty() {
        bail!("at least one dynamic library name is required");
    }

    let file = syn::parse_file(source).context("failed to parse bindgen Rust output")?;
    let mut items = Vec::new();
    let mut functions = Vec::new();

    for item in file.items {
        match item {
            Item::ForeignMod(foreign_mod) => {
                let abi = foreign_mod.abi.clone();

                for foreign_item in foreign_mod.items {
                    match foreign_item {
                        ForeignItem::Fn(func) if func.sig.variadic.is_none() => {
                            functions.push(Function {
                                attrs: func.attrs,
                                vis: func.vis,
                                sig: func.sig,
                                abi: abi.clone(),
                            });
                        }
                        ForeignItem::Fn(_) => {}
                        _ => {}
                    }
                }
            }
            other => items.push(other),
        }
    }

    let file_attrs = file.attrs;
    let helper = loader_tokens(library_names);
    let adapters = functions
        .iter()
        .map(adapter_tokens)
        .collect::<Result<Vec<_>>>()?;

    let tokens = quote! {
        #(#file_attrs)*

        #helper

        #(#items)*

        #(#adapters)*
    };

    let parsed = syn::parse2::<syn::File>(tokens).context("generated invalid Rust tokens")?;
    let source = format!(
        "// Automatically generated by koharu-bindgen. Do not edit by hand.\n\n{}",
        prettyplease::unparse(&parsed)
    );

    Ok(source)
}

fn loader_tokens(library_names: &[String]) -> TokenStream {
    let library_names = library_names
        .iter()
        .map(|library_name| LitStr::new(library_name, Span::call_site()))
        .collect::<Vec<_>>();

    quote! {
        const __KOHARU_BINDGEN_LIBRARY_NAMES: &[&str] = &[#(#library_names),*];

        static __KOHARU_BINDGEN_LIBRARIES: ::std::sync::OnceLock<::std::vec::Vec<::libloading::Library>> =
            ::std::sync::OnceLock::new();

        fn __koharu_bindgen_library_file_name(library_name: &str) -> ::std::string::String {
            if cfg!(target_os = "windows") {
                ::std::format!("{library_name}.dll")
            } else if cfg!(target_os = "macos") {
                ::std::format!("lib{library_name}.dylib")
            } else {
                ::std::format!("lib{library_name}.so")
            }
        }

        fn __koharu_bindgen_bundled_library_paths(
            library_file_name: &str,
        ) -> ::std::vec::Vec<::std::path::PathBuf> {
            // A bundled app's working directory is not necessarily its executable directory.
            let Some(directory) = ::std::env::current_exe()
                .ok()
                .and_then(|executable| executable.parent().map(::std::path::Path::to_owned))
            else {
                return ::std::vec::Vec::new();
            };

            let mut paths = ::std::vec::Vec::new();
            #[cfg(target_os = "macos")]
            if let Some(contents) = directory.parent() {
                paths.push(contents.join("Frameworks").join(library_file_name));
            }
            paths.push(directory.join(library_file_name));
            paths
        }

        #[cfg(target_os = "windows")]
        fn __koharu_bindgen_already_loaded_library(
            library_file_name: &str,
        ) -> ::std::option::Option<::libloading::Library> {
            ::libloading::os::windows::Library::open_already_loaded(library_file_name)
                .ok()
                .map(::std::convert::Into::into)
        }

        #[cfg(target_os = "linux")]
        fn __koharu_bindgen_already_loaded_library(
            library_file_name: &str,
        ) -> ::std::option::Option<::libloading::Library> {
            unsafe {
                ::libloading::os::unix::Library::open(
                    Some(library_file_name),
                    ::libloading::os::unix::RTLD_LAZY | ::libc::RTLD_NOLOAD,
                )
            }
            .ok()
            .map(::std::convert::Into::into)
        }

        #[cfg(not(any(target_os = "windows", target_os = "linux")))]
        fn __koharu_bindgen_already_loaded_library(
            _library_file_name: &str,
        ) -> ::std::option::Option<::libloading::Library> {
            None
        }

        unsafe fn __koharu_bindgen_open_library(
            library_file_name: &str,
        ) -> ::std::result::Result<::libloading::Library, ::std::string::String> {
            // Reuse a library brought into the process by another dependency first.
            if let Some(library) = __koharu_bindgen_already_loaded_library(library_file_name) {
                return Ok(library);
            }

            for path in __koharu_bindgen_bundled_library_paths(library_file_name) {
                if let Ok(library) = unsafe { ::libloading::Library::new(path) } {
                    return Ok(library);
                }
            }
            unsafe { ::libloading::Library::new(library_file_name) }
                .map_err(|error| error.to_string())
        }

        unsafe fn __koharu_bindgen_libraries() -> &'static [::libloading::Library] {
            __KOHARU_BINDGEN_LIBRARIES.get_or_init(|| {
                let mut libraries = ::std::vec::Vec::new();
                let mut errors = ::std::vec::Vec::new();

                for library_name in __KOHARU_BINDGEN_LIBRARY_NAMES {
                    let library_file_name = __koharu_bindgen_library_file_name(library_name);
                    match unsafe { __koharu_bindgen_open_library(&library_file_name) } {
                        Ok(library) => libraries.push(library),
                        Err(error) => errors.push(::std::format!("{library_file_name}: {error}")),
                    }
                }

                if libraries.is_empty() {
                    panic!(
                        "failed to load any dynamic library from [{}]: {}",
                        __KOHARU_BINDGEN_LIBRARY_NAMES.join(", "),
                        errors.join("; ")
                    );
                }

                libraries
            }).as_slice()
        }

        unsafe fn __koharu_bindgen_load<F: Copy>(name: &[u8]) -> F {
            for library in unsafe { __koharu_bindgen_libraries() } {
                if let Ok(symbol) = unsafe { library.get::<F>(name) } {
                    return *symbol;
                }
            }

            panic!(
                "missing symbol {} in dynamic libraries [{}]",
                ::std::string::String::from_utf8_lossy(name)
                    .trim_end_matches('\0'),
                __KOHARU_BINDGEN_LIBRARY_NAMES.join(", ")
            )
        }

    }
}

fn adapter_tokens(function: &Function) -> Result<TokenStream> {
    if !function.sig.generics.params.is_empty() {
        bail!(
            "cannot generate adapter for generic foreign function `{}`",
            function.sig.ident
        );
    }

    let attrs = function
        .attrs
        .iter()
        .filter(|attr| !is_link_attr(attr))
        .collect::<Vec<_>>();
    let vis = &function.vis;
    let fn_name = &function.sig.ident;
    let abi = &function.abi;
    let output = &function.sig.output;
    let symbol = LitStr::new(&symbol_name(function), Span::call_site());
    let signature = adapter_signature(&function.sig)?;
    let wrapper_inputs = &signature.wrapper_inputs;
    let arg_names = &signature.arg_names;
    let arg_types = &signature.arg_types;

    Ok(quote! {
        #(#attrs)*
        #vis unsafe fn #fn_name(#(#wrapper_inputs),*) #output {
            type FnPtr = unsafe #abi fn(#(#arg_types),*) #output;
            static FN: ::std::sync::OnceLock<FnPtr> = ::std::sync::OnceLock::new();
            let function = FN.get_or_init(|| unsafe {
                __koharu_bindgen_load::<FnPtr>(concat!(#symbol, "\0").as_bytes())
            });
            unsafe { function(#(#arg_names),*) }
        }
    })
}

struct AdapterSignature {
    wrapper_inputs: Vec<TokenStream>,
    arg_names: Vec<syn::Ident>,
    arg_types: Vec<Type>,
}

fn adapter_signature(sig: &Signature) -> Result<AdapterSignature> {
    let mut wrapper_inputs = Vec::new();
    let mut arg_names = Vec::new();
    let mut arg_types = Vec::new();
    let mut used_arg_names = HashSet::new();

    for (index, input) in sig.inputs.iter().enumerate() {
        let FnArg::Typed(pat_type) = input else {
            bail!(
                "unsupported receiver argument in foreign function `{}`",
                sig.ident
            );
        };

        let ty = adapter_type(pat_type.ty.as_ref());
        let mut ident = match pat_type.pat.as_ref() {
            Pat::Ident(ident) if ident.ident != "_" => ident.ident.clone(),
            _ => format_ident!("arg_{index}"),
        };
        if !used_arg_names.insert(ident.to_string()) {
            ident = format_ident!("arg_{index}");
            while !used_arg_names.insert(ident.to_string()) {
                ident = format_ident!("arg_{}", used_arg_names.len());
            }
        }

        wrapper_inputs.push(quote! { #ident: #ty });
        arg_names.push(ident);
        arg_types.push(ty);
    }

    Ok(AdapterSignature {
        wrapper_inputs,
        arg_names,
        arg_types,
    })
}

fn adapter_type(ty: &Type) -> Type {
    let Type::Path(path) = ty else {
        return ty.clone();
    };
    if path.qself.is_some() {
        return ty.clone();
    }

    let Some(segment) = path.path.segments.last() else {
        return ty.clone();
    };
    if segment.ident != "Option" {
        return ty.clone();
    }

    let PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return ty.clone();
    };
    if arguments.args.len() != 1 {
        return ty.clone();
    }

    let Some(GenericArgument::Type(Type::FnPtr(function))) = arguments.args.first() else {
        return ty.clone();
    };

    let mut function = function.clone();
    function.unsafety = None;
    Type::FnPtr(function)
}

fn symbol_name(function: &Function) -> String {
    function
        .attrs
        .iter()
        .find_map(link_name)
        .unwrap_or_else(|| function.sig.ident.to_string())
        .trim_start_matches('\u{1}')
        .to_owned()
}

fn link_name(attr: &Attribute) -> Option<String> {
    let Meta::NameValue(meta) = &attr.meta else {
        return None;
    };
    if !meta.path.is_ident("link_name") {
        return None;
    }
    let Expr::Lit(ExprLit {
        lit: Lit::Str(value),
        ..
    }) = &meta.value
    else {
        return None;
    };
    Some(value.value())
}

fn is_link_attr(attr: &Attribute) -> bool {
    attr.path().is_ident("link_name") || attr.path().is_ident("link_ordinal")
}
