/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type {
  ApiError,
  CreateTextBlock,
  TextBlockDetail,
  TextBlockInput,
  TextBlockPatch,
} from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getPutTextBlocksUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/text-blocks`
}

export const putTextBlocks = async (
  documentId: string,
  textBlockInput: TextBlockInput[],
  options?: RequestInit,
): Promise<void> => {
  return fetchApi<void>(getPutTextBlocksUrl(documentId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(textBlockInput),
  })
}

export const getPutTextBlocksMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTextBlocks>>,
    TError,
    { documentId: string; data: TextBlockInput[] },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTextBlocks>>,
  TError,
  { documentId: string; data: TextBlockInput[] },
  TContext
> => {
  const mutationKey = ['putTextBlocks']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTextBlocks>>,
    { documentId: string; data: TextBlockInput[] }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return putTextBlocks(documentId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutTextBlocksMutationResult = NonNullable<Awaited<ReturnType<typeof putTextBlocks>>>
export type PutTextBlocksMutationBody = TextBlockInput[]
export type PutTextBlocksMutationError = ApiError

export const usePutTextBlocks = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTextBlocks>>,
      TError,
      { documentId: string; data: TextBlockInput[] },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTextBlocks>>,
  TError,
  { documentId: string; data: TextBlockInput[] },
  TContext
> => {
  return useMutation(getPutTextBlocksMutationOptions(options), queryClient)
}
export const getCreateTextBlockUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/text-blocks`
}

export const createTextBlock = async (
  documentId: string,
  createTextBlock: CreateTextBlock,
  options?: RequestInit,
): Promise<TextBlockDetail> => {
  return fetchApi<TextBlockDetail>(getCreateTextBlockUrl(documentId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTextBlock),
  })
}

export const getCreateTextBlockMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTextBlock>>,
    TError,
    { documentId: string; data: CreateTextBlock },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTextBlock>>,
  TError,
  { documentId: string; data: CreateTextBlock },
  TContext
> => {
  const mutationKey = ['createTextBlock']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTextBlock>>,
    { documentId: string; data: CreateTextBlock }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return createTextBlock(documentId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateTextBlockMutationResult = NonNullable<Awaited<ReturnType<typeof createTextBlock>>>
export type CreateTextBlockMutationBody = CreateTextBlock
export type CreateTextBlockMutationError = ApiError

export const useCreateTextBlock = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTextBlock>>,
      TError,
      { documentId: string; data: CreateTextBlock },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTextBlock>>,
  TError,
  { documentId: string; data: CreateTextBlock },
  TContext
> => {
  return useMutation(getCreateTextBlockMutationOptions(options), queryClient)
}
export const getDeleteTextBlockUrl = (documentId: string, textBlockId: string) => {
  return `/api/v1/documents/${documentId}/text-blocks/${textBlockId}`
}

export const deleteTextBlock = async (
  documentId: string,
  textBlockId: string,
  options?: RequestInit,
): Promise<void> => {
  return fetchApi<void>(getDeleteTextBlockUrl(documentId, textBlockId), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteTextBlockMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTextBlock>>,
    TError,
    { documentId: string; textBlockId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTextBlock>>,
  TError,
  { documentId: string; textBlockId: string },
  TContext
> => {
  const mutationKey = ['deleteTextBlock']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTextBlock>>,
    { documentId: string; textBlockId: string }
  > = (props) => {
    const { documentId, textBlockId } = props ?? {}

    return deleteTextBlock(documentId, textBlockId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteTextBlockMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTextBlock>>>

export type DeleteTextBlockMutationError = ApiError

export const useDeleteTextBlock = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTextBlock>>,
      TError,
      { documentId: string; textBlockId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTextBlock>>,
  TError,
  { documentId: string; textBlockId: string },
  TContext
> => {
  return useMutation(getDeleteTextBlockMutationOptions(options), queryClient)
}
export const getPatchTextBlockUrl = (documentId: string, textBlockId: string) => {
  return `/api/v1/documents/${documentId}/text-blocks/${textBlockId}`
}

export const patchTextBlock = async (
  documentId: string,
  textBlockId: string,
  textBlockPatch: TextBlockPatch,
  options?: RequestInit,
): Promise<TextBlockDetail> => {
  return fetchApi<TextBlockDetail>(getPatchTextBlockUrl(documentId, textBlockId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(textBlockPatch),
  })
}

export const getPatchTextBlockMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTextBlock>>,
    TError,
    { documentId: string; textBlockId: string; data: TextBlockPatch },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchTextBlock>>,
  TError,
  { documentId: string; textBlockId: string; data: TextBlockPatch },
  TContext
> => {
  const mutationKey = ['patchTextBlock']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchTextBlock>>,
    { documentId: string; textBlockId: string; data: TextBlockPatch }
  > = (props) => {
    const { documentId, textBlockId, data } = props ?? {}

    return patchTextBlock(documentId, textBlockId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchTextBlockMutationResult = NonNullable<Awaited<ReturnType<typeof patchTextBlock>>>
export type PatchTextBlockMutationBody = TextBlockPatch
export type PatchTextBlockMutationError = ApiError

export const usePatchTextBlock = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchTextBlock>>,
      TError,
      { documentId: string; textBlockId: string; data: TextBlockPatch },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchTextBlock>>,
  TError,
  { documentId: string; textBlockId: string; data: TextBlockPatch },
  TContext
> => {
  return useMutation(getPatchTextBlockMutationOptions(options), queryClient)
}
