/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type { ApiError, JobState, PipelineJobRequest } from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getListJobsUrl = () => {
  return `/api/v1/jobs`
}

export const listJobs = async (options?: RequestInit): Promise<JobState[]> => {
  return fetchApi<JobState[]>(getListJobsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getListJobsQueryKey = () => {
  return [`/api/v1/jobs`] as const
}

export const getListJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof listJobs>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListJobsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listJobs>>> = ({ signal }) =>
    listJobs({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type ListJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listJobs>>>
export type ListJobsQueryError = unknown

export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJobs>>,
          TError,
          Awaited<ReturnType<typeof listJobs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListJobsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getStartPipelineUrl = () => {
  return `/api/v1/jobs/pipeline`
}

export const startPipeline = async (
  pipelineJobRequest: PipelineJobRequest,
  options?: RequestInit,
): Promise<JobState> => {
  return fetchApi<JobState>(getStartPipelineUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pipelineJobRequest),
  })
}

export const getStartPipelineMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startPipeline>>,
    TError,
    { data: PipelineJobRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof startPipeline>>,
  TError,
  { data: PipelineJobRequest },
  TContext
> => {
  const mutationKey = ['startPipeline']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startPipeline>>,
    { data: PipelineJobRequest }
  > = (props) => {
    const { data } = props ?? {}

    return startPipeline(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartPipelineMutationResult = NonNullable<Awaited<ReturnType<typeof startPipeline>>>
export type StartPipelineMutationBody = PipelineJobRequest
export type StartPipelineMutationError = ApiError

export const useStartPipeline = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startPipeline>>,
      TError,
      { data: PipelineJobRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startPipeline>>,
  TError,
  { data: PipelineJobRequest },
  TContext
> => {
  return useMutation(getStartPipelineMutationOptions(options), queryClient)
}
export const getGetJobUrl = (jobId: string) => {
  return `/api/v1/jobs/${jobId}`
}

export const getJob = async (jobId: string, options?: RequestInit): Promise<JobState> => {
  return fetchApi<JobState>(getGetJobUrl(jobId), {
    ...options,
    method: 'GET',
  })
}

export const getGetJobQueryKey = (jobId: string) => {
  return [`/api/v1/jobs/${jobId}`] as const
}

export const getGetJobQueryOptions = <
  TData = Awaited<ReturnType<typeof getJob>>,
  TError = ApiError,
>(
  jobId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetJobQueryKey(jobId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJob>>> = ({ signal }) =>
    getJob(jobId, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!jobId,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetJobQueryResult = NonNullable<Awaited<ReturnType<typeof getJob>>>
export type GetJobQueryError = ApiError

export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = ApiError>(
  jobId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = ApiError>(
  jobId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJob>>,
          TError,
          Awaited<ReturnType<typeof getJob>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = ApiError>(
  jobId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = ApiError>(
  jobId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetJobQueryOptions(jobId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getCancelJobUrl = (jobId: string) => {
  return `/api/v1/jobs/${jobId}`
}

export const cancelJob = async (jobId: string, options?: RequestInit): Promise<void> => {
  return fetchApi<void>(getCancelJobUrl(jobId), {
    ...options,
    method: 'DELETE',
  })
}

export const getCancelJobMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelJob>>,
    TError,
    { jobId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelJob>>,
  TError,
  { jobId: string },
  TContext
> => {
  const mutationKey = ['cancelJob']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelJob>>, { jobId: string }> = (
    props,
  ) => {
    const { jobId } = props ?? {}

    return cancelJob(jobId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CancelJobMutationResult = NonNullable<Awaited<ReturnType<typeof cancelJob>>>

export type CancelJobMutationError = ApiError

export const useCancelJob = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelJob>>,
      TError,
      { jobId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelJob>>,
  TError,
  { jobId: string },
  TContext
> => {
  return useMutation(getCancelJobMutationOptions(options), queryClient)
}
