/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type {
  ApiError,
  FontFaceInfo,
  GetConfig200,
  GetEngineCatalog200,
  GoogleFontCatalogResponse,
  MetaInfo,
  UpdateConfig200,
  UpdateConfigBody,
} from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getGetConfigUrl = () => {
  return `/api/v1/config`
}

export const getConfig = async (options?: RequestInit): Promise<GetConfig200> => {
  return fetchApi<GetConfig200>(getGetConfigUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetConfigQueryKey = () => {
  return [`/api/v1/config`] as const
}

export const getGetConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getConfig>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetConfigQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfig>>> = ({ signal }) =>
    getConfig({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getConfig>>>
export type GetConfigQueryError = ApiError

export function useGetConfig<TData = Awaited<ReturnType<typeof getConfig>>, TError = ApiError>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfig>>,
          TError,
          Awaited<ReturnType<typeof getConfig>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetConfig<TData = Awaited<ReturnType<typeof getConfig>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfig>>,
          TError,
          Awaited<ReturnType<typeof getConfig>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetConfig<TData = Awaited<ReturnType<typeof getConfig>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetConfig<TData = Awaited<ReturnType<typeof getConfig>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfig>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getUpdateConfigUrl = () => {
  return `/api/v1/config`
}

export const updateConfig = async (
  updateConfigBody: UpdateConfigBody,
  options?: RequestInit,
): Promise<UpdateConfig200> => {
  return fetchApi<UpdateConfig200>(getUpdateConfigUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateConfigBody),
  })
}

export const getUpdateConfigMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateConfig>>,
    TError,
    { data: UpdateConfigBody },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateConfig>>,
  TError,
  { data: UpdateConfigBody },
  TContext
> => {
  const mutationKey = ['updateConfig']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateConfig>>,
    { data: UpdateConfigBody }
  > = (props) => {
    const { data } = props ?? {}

    return updateConfig(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateConfig>>>
export type UpdateConfigMutationBody = UpdateConfigBody
export type UpdateConfigMutationError = ApiError

export const useUpdateConfig = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateConfig>>,
      TError,
      { data: UpdateConfigBody },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateConfig>>,
  TError,
  { data: UpdateConfigBody },
  TContext
> => {
  return useMutation(getUpdateConfigMutationOptions(options), queryClient)
}
export const getGetEngineCatalogUrl = () => {
  return `/api/v1/engines`
}

export const getEngineCatalog = async (options?: RequestInit): Promise<GetEngineCatalog200> => {
  return fetchApi<GetEngineCatalog200>(getGetEngineCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetEngineCatalogQueryKey = () => {
  return [`/api/v1/engines`] as const
}

export const getGetEngineCatalogQueryOptions = <
  TData = Awaited<ReturnType<typeof getEngineCatalog>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetEngineCatalogQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEngineCatalog>>> = ({ signal }) =>
    getEngineCatalog({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetEngineCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getEngineCatalog>>>
export type GetEngineCatalogQueryError = unknown

export function useGetEngineCatalog<
  TData = Awaited<ReturnType<typeof getEngineCatalog>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEngineCatalog>>,
          TError,
          Awaited<ReturnType<typeof getEngineCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetEngineCatalog<
  TData = Awaited<ReturnType<typeof getEngineCatalog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEngineCatalog>>,
          TError,
          Awaited<ReturnType<typeof getEngineCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetEngineCatalog<
  TData = Awaited<ReturnType<typeof getEngineCatalog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetEngineCatalog<
  TData = Awaited<ReturnType<typeof getEngineCatalog>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEngineCatalog>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetEngineCatalogQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getListFontsUrl = () => {
  return `/api/v1/fonts`
}

export const listFonts = async (options?: RequestInit): Promise<FontFaceInfo[]> => {
  return fetchApi<FontFaceInfo[]>(getListFontsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getListFontsQueryKey = () => {
  return [`/api/v1/fonts`] as const
}

export const getListFontsQueryOptions = <
  TData = Awaited<ReturnType<typeof listFonts>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListFontsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFonts>>> = ({ signal }) =>
    listFonts({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type ListFontsQueryResult = NonNullable<Awaited<ReturnType<typeof listFonts>>>
export type ListFontsQueryError = ApiError

export function useListFonts<TData = Awaited<ReturnType<typeof listFonts>>, TError = ApiError>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFonts>>,
          TError,
          Awaited<ReturnType<typeof listFonts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListFonts<TData = Awaited<ReturnType<typeof listFonts>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFonts>>,
          TError,
          Awaited<ReturnType<typeof listFonts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListFonts<TData = Awaited<ReturnType<typeof listFonts>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useListFonts<TData = Awaited<ReturnType<typeof listFonts>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFonts>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListFontsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetGoogleFontsCatalogUrl = () => {
  return `/api/v1/fonts/google/catalog`
}

export const getGoogleFontsCatalog = async (
  options?: RequestInit,
): Promise<GoogleFontCatalogResponse> => {
  return fetchApi<GoogleFontCatalogResponse>(getGetGoogleFontsCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetGoogleFontsCatalogQueryKey = () => {
  return [`/api/v1/fonts/google/catalog`] as const
}

export const getGetGoogleFontsCatalogQueryOptions = <
  TData = Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetGoogleFontsCatalogQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGoogleFontsCatalog>>> = ({ signal }) =>
    getGoogleFontsCatalog({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetGoogleFontsCatalogQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGoogleFontsCatalog>>
>
export type GetGoogleFontsCatalogQueryError = ApiError

export function useGetGoogleFontsCatalog<
  TData = Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
          TError,
          Awaited<ReturnType<typeof getGoogleFontsCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetGoogleFontsCatalog<
  TData = Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
          TError,
          Awaited<ReturnType<typeof getGoogleFontsCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetGoogleFontsCatalog<
  TData = Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetGoogleFontsCatalog<
  TData = Awaited<ReturnType<typeof getGoogleFontsCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontsCatalog>>, TError, TData>
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetGoogleFontsCatalogQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getFetchGoogleFontUrl = (family: string) => {
  return `/api/v1/fonts/google/${family}/fetch`
}

export const fetchGoogleFont = async (
  family: string,
  options?: RequestInit,
): Promise<FontFaceInfo> => {
  return fetchApi<FontFaceInfo>(getFetchGoogleFontUrl(family), {
    ...options,
    method: 'POST',
  })
}

export const getFetchGoogleFontMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof fetchGoogleFont>>,
    TError,
    { family: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof fetchGoogleFont>>,
  TError,
  { family: string },
  TContext
> => {
  const mutationKey = ['fetchGoogleFont']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof fetchGoogleFont>>,
    { family: string }
  > = (props) => {
    const { family } = props ?? {}

    return fetchGoogleFont(family, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type FetchGoogleFontMutationResult = NonNullable<Awaited<ReturnType<typeof fetchGoogleFont>>>

export type FetchGoogleFontMutationError = ApiError

export const useFetchGoogleFont = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof fetchGoogleFont>>,
      TError,
      { family: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof fetchGoogleFont>>,
  TError,
  { family: string },
  TContext
> => {
  return useMutation(getFetchGoogleFontMutationOptions(options), queryClient)
}
export const getGetGoogleFontFileUrl = (family: string) => {
  return `/api/v1/fonts/google/${family}/file`
}

export const getGoogleFontFile = async (family: string, options?: RequestInit): Promise<Blob> => {
  return fetchApi<Blob>(getGetGoogleFontFileUrl(family), {
    ...options,
    method: 'GET',
  })
}

export const getGetGoogleFontFileQueryKey = (family: string) => {
  return [`/api/v1/fonts/google/${family}/file`] as const
}

export const getGetGoogleFontFileQueryOptions = <
  TData = Awaited<ReturnType<typeof getGoogleFontFile>>,
  TError = ApiError,
>(
  family: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetGoogleFontFileQueryKey(family)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGoogleFontFile>>> = ({ signal }) =>
    getGoogleFontFile(family, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!family,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetGoogleFontFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGoogleFontFile>>
>
export type GetGoogleFontFileQueryError = ApiError

export function useGetGoogleFontFile<
  TData = Awaited<ReturnType<typeof getGoogleFontFile>>,
  TError = ApiError,
>(
  family: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoogleFontFile>>,
          TError,
          Awaited<ReturnType<typeof getGoogleFontFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetGoogleFontFile<
  TData = Awaited<ReturnType<typeof getGoogleFontFile>>,
  TError = ApiError,
>(
  family: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoogleFontFile>>,
          TError,
          Awaited<ReturnType<typeof getGoogleFontFile>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetGoogleFontFile<
  TData = Awaited<ReturnType<typeof getGoogleFontFile>>,
  TError = ApiError,
>(
  family: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetGoogleFontFile<
  TData = Awaited<ReturnType<typeof getGoogleFontFile>>,
  TError = ApiError,
>(
  family: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleFontFile>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetGoogleFontFileQueryOptions(family, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getGetMetaUrl = () => {
  return `/api/v1/meta`
}

export const getMeta = async (options?: RequestInit): Promise<MetaInfo> => {
  return fetchApi<MetaInfo>(getGetMetaUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetMetaQueryKey = () => {
  return [`/api/v1/meta`] as const
}

export const getGetMetaQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeta>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMetaQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeta>>> = ({ signal }) =>
    getMeta({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetMetaQueryResult = NonNullable<Awaited<ReturnType<typeof getMeta>>>
export type GetMetaQueryError = ApiError

export function useGetMeta<TData = Awaited<ReturnType<typeof getMeta>>, TError = ApiError>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeta>>,
          TError,
          Awaited<ReturnType<typeof getMeta>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMeta<TData = Awaited<ReturnType<typeof getMeta>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeta>>,
          TError,
          Awaited<ReturnType<typeof getMeta>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMeta<TData = Awaited<ReturnType<typeof getMeta>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetMeta<TData = Awaited<ReturnType<typeof getMeta>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeta>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMetaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
