[package]
name = "koharu-psd"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
image = { workspace = true }
koharu-renderer = { workspace = true }
koharu-rasterizer = { workspace = true, features = ["native"] }
koharu-scene = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
