/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type { ApiError, RenderRequest, TranslateRequest } from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getDetectDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/detect`
}

export const detectDocument = async (documentId: string, options?: RequestInit): Promise<void> => {
  return fetchApi<void>(getDetectDocumentUrl(documentId), {
    ...options,
    method: 'POST',
  })
}

export const getDetectDocumentMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof detectDocument>>,
    TError,
    { documentId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof detectDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  const mutationKey = ['detectDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof detectDocument>>,
    { documentId: string }
  > = (props) => {
    const { documentId } = props ?? {}

    return detectDocument(documentId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DetectDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof detectDocument>>>

export type DetectDocumentMutationError = ApiError

export const useDetectDocument = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof detectDocument>>,
      TError,
      { documentId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof detectDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  return useMutation(getDetectDocumentMutationOptions(options), queryClient)
}
export const getInpaintDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/inpaint`
}

export const inpaintDocument = async (documentId: string, options?: RequestInit): Promise<void> => {
  return fetchApi<void>(getInpaintDocumentUrl(documentId), {
    ...options,
    method: 'POST',
  })
}

export const getInpaintDocumentMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inpaintDocument>>,
    TError,
    { documentId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof inpaintDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  const mutationKey = ['inpaintDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inpaintDocument>>,
    { documentId: string }
  > = (props) => {
    const { documentId } = props ?? {}

    return inpaintDocument(documentId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type InpaintDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof inpaintDocument>>>

export type InpaintDocumentMutationError = ApiError

export const useInpaintDocument = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inpaintDocument>>,
      TError,
      { documentId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inpaintDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  return useMutation(getInpaintDocumentMutationOptions(options), queryClient)
}
export const getRecognizeDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/recognize`
}

export const recognizeDocument = async (
  documentId: string,
  options?: RequestInit,
): Promise<void> => {
  return fetchApi<void>(getRecognizeDocumentUrl(documentId), {
    ...options,
    method: 'POST',
  })
}

export const getRecognizeDocumentMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recognizeDocument>>,
    TError,
    { documentId: string },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof recognizeDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  const mutationKey = ['recognizeDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recognizeDocument>>,
    { documentId: string }
  > = (props) => {
    const { documentId } = props ?? {}

    return recognizeDocument(documentId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RecognizeDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof recognizeDocument>>
>

export type RecognizeDocumentMutationError = ApiError

export const useRecognizeDocument = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recognizeDocument>>,
      TError,
      { documentId: string },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recognizeDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  return useMutation(getRecognizeDocumentMutationOptions(options), queryClient)
}
export const getRenderDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/render`
}

export const renderDocument = async (
  documentId: string,
  renderRequest: RenderRequest,
  options?: RequestInit,
): Promise<void> => {
  return fetchApi<void>(getRenderDocumentUrl(documentId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(renderRequest),
  })
}

export const getRenderDocumentMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof renderDocument>>,
    TError,
    { documentId: string; data: RenderRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof renderDocument>>,
  TError,
  { documentId: string; data: RenderRequest },
  TContext
> => {
  const mutationKey = ['renderDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof renderDocument>>,
    { documentId: string; data: RenderRequest }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return renderDocument(documentId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RenderDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof renderDocument>>>
export type RenderDocumentMutationBody = RenderRequest
export type RenderDocumentMutationError = ApiError

export const useRenderDocument = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof renderDocument>>,
      TError,
      { documentId: string; data: RenderRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof renderDocument>>,
  TError,
  { documentId: string; data: RenderRequest },
  TContext
> => {
  return useMutation(getRenderDocumentMutationOptions(options), queryClient)
}
export const getTranslateDocumentUrl = (documentId: string) => {
  return `/api/v1/documents/${documentId}/translate`
}

export const translateDocument = async (
  documentId: string,
  translateRequest: TranslateRequest,
  options?: RequestInit,
): Promise<void> => {
  return fetchApi<void>(getTranslateDocumentUrl(documentId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(translateRequest),
  })
}

export const getTranslateDocumentMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof translateDocument>>,
    TError,
    { documentId: string; data: TranslateRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof translateDocument>>,
  TError,
  { documentId: string; data: TranslateRequest },
  TContext
> => {
  const mutationKey = ['translateDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof translateDocument>>,
    { documentId: string; data: TranslateRequest }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return translateDocument(documentId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TranslateDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof translateDocument>>
>
export type TranslateDocumentMutationBody = TranslateRequest
export type TranslateDocumentMutationError = ApiError

export const useTranslateDocument = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof translateDocument>>,
      TError,
      { documentId: string; data: TranslateRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof translateDocument>>,
  TError,
  { documentId: string; data: TranslateRequest },
  TContext
> => {
  return useMutation(getTranslateDocumentMutationOptions(options), queryClient)
}
