/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface DocumentSummary {
  hasBrushLayer: boolean
  hasInpainted: boolean
  hasRendered: boolean
  hasSegment: boolean
  /** @minimum 0 */
  height: number
  id: string
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 0 */
  textBlockCount: number
  /** @minimum 0 */
  width: number
}
