/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type LlmStateStatus = (typeof LlmStateStatus)[keyof typeof LlmStateStatus]

export const LlmStateStatus = {
  empty: 'empty',
  loading: 'loading',
  ready: 'ready',
  failed: 'failed',
} as const
