/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type TransferStatus = (typeof TransferStatus)[keyof typeof TransferStatus]

export const TransferStatus = {
  started: 'started',
  downloading: 'downloading',
  completed: 'completed',
  failed: 'failed',
} as const
