export const selectors = {
  menu: {
    fileTrigger: 'menu-file-trigger',
    fileOpen: 'menu-file-open',
    fileAdd: 'menu-file-add',
    fileExport: 'menu-file-export',
    fileExportAllInpainted: 'menu-file-export-all-inpainted',
    fileExportAllRendered: 'menu-file-export-all-rendered',
    processTrigger: 'menu-process-trigger',
    processCurrent: 'menu-process-current',
    processRerender: 'menu-process-rerender',
    processAll: 'menu-process-all',
  },
  navigator: {
    panel: 'navigator-panel',
    page: (index: number) => `navigator-page-${index}`,
    pageManagerButton: 'navigator-manage-pages',
  },
  pageManager: {
    dialog: 'page-manager-dialog',
    grid: 'page-manager-grid',
    card: (index: number) => `page-manager-card-${index}`,
    save: 'page-manager-save',
  },
  workspace: {
    viewport: 'workspace-viewport',
    canvas: 'workspace-canvas',
    maskCanvas: 'workspace-mask-canvas',
    brushCanvas: 'workspace-brush-canvas',
    brushDisplayCanvas: 'workspace-brush-display-canvas',
    renderedImage: 'workspace-rendered-image',
    inpaintedImage: 'workspace-inpainted-image',
    annotations: 'workspace-annotations',
  },
  zoom: {
    slider: 'zoom-slider',
    value: 'zoom-value',
  },
  toolbar: {
    detect: 'toolbar-detect',
    ocr: 'toolbar-ocr',
    translate: 'toolbar-translate',
    inpaint: 'toolbar-inpaint',
    render: 'toolbar-render',
  },
  llm: {
    trigger: 'llm-trigger',
    popover: 'llm-popover',
    modelSearch: 'llm-model-search',
    modelSelect: 'llm-model-select',
    modelOption: (index: number) => `llm-model-option-${index}`,
    modelEmpty: 'llm-model-empty',
    languageSelect: 'llm-language-select',
    languageOption: (index: number) => `llm-language-option-${index}`,
    loadToggle: 'llm-load-toggle',
  },
  tools: {
    select: 'tool-select',
    block: 'tool-block',
    brush: 'tool-brush',
    eraser: 'tool-eraser',
    repairBrush: 'tool-repairBrush',
    brushSizeSlider: 'brush-size-slider',
    brushColorTrigger: 'brush-color-trigger',
    brushColorPicker: 'brush-color-picker',
    brushColorSwatch: 'brush-color-swatch',
  },
  panels: {
    layers: 'panels-layers',
    layout: 'panels-layout',
    tabLayers: 'panels-tab-layers',
    tabLayout: 'panels-tab-layout',
    textBlocks: 'panels-textblocks',
    textBlocksCount: 'textblocks-count',
    textBlocksScroll: 'textblocks-scroll',
    textBlockCard: (index: number) => `textblock-card-${index}`,
    textBlockOcr: (index: number) => `textblock-ocr-${index}`,
    textBlockTranslation: (index: number) => `textblock-translation-${index}`,
    textBlockDelete: (index: number) => `textblock-delete-${index}`,
    textBlockGenerate: (index: number) => `textblock-generate-${index}`,
    renderFontSelect: 'render-font-select',
    renderFontOption: (index: number) => `render-font-option-${index}`,
    renderEffectToggle: (effect: 'italic' | 'bold' | 'border') =>
      `render-effect-toggle-${effect}`,
    renderColorTrigger: 'render-color-trigger',
    renderColorPicker: 'render-color-picker',
    renderColorSwatch: 'render-color-swatch',
  },
  layers: {
    rendered: 'layer-rendered',
    textBlocks: 'layer-textBlocks',
    brush: 'layer-brush',
    inpainted: 'layer-inpainted',
    mask: 'layer-mask',
    base: 'layer-base',
  },
  operations: {
    card: 'operation-card',
    cancel: 'operation-cancel',
  },
} as const

export type LayerId = keyof typeof selectors.layers
