/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { fetchApi } from '.././fetch'
import type { ApiError, LlmCatalog, LlmLoadRequest, LlmState } from '../schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getGetLlmUrl = () => {
  return `/api/v1/llm`
}

export const getLlm = async (options?: RequestInit): Promise<LlmState> => {
  return fetchApi<LlmState>(getGetLlmUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetLlmQueryKey = () => {
  return [`/api/v1/llm`] as const
}

export const getGetLlmQueryOptions = <
  TData = Awaited<ReturnType<typeof getLlm>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetLlmQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLlm>>> = ({ signal }) =>
    getLlm({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetLlmQueryResult = NonNullable<Awaited<ReturnType<typeof getLlm>>>
export type GetLlmQueryError = ApiError

export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlm>>,
          TError,
          Awaited<ReturnType<typeof getLlm>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlm>>,
          TError,
          Awaited<ReturnType<typeof getLlm>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetLlmQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getLoadLlmUrl = () => {
  return `/api/v1/llm`
}

export const loadLlm = async (
  llmLoadRequest: LlmLoadRequest,
  options?: RequestInit,
): Promise<LlmState> => {
  return fetchApi<LlmState>(getLoadLlmUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(llmLoadRequest),
  })
}

export const getLoadLlmMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loadLlm>>,
    TError,
    { data: LlmLoadRequest },
    TContext
  >
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof loadLlm>>,
  TError,
  { data: LlmLoadRequest },
  TContext
> => {
  const mutationKey = ['loadLlm']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loadLlm>>,
    { data: LlmLoadRequest }
  > = (props) => {
    const { data } = props ?? {}

    return loadLlm(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoadLlmMutationResult = NonNullable<Awaited<ReturnType<typeof loadLlm>>>
export type LoadLlmMutationBody = LlmLoadRequest
export type LoadLlmMutationError = ApiError

export const useLoadLlm = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loadLlm>>,
      TError,
      { data: LlmLoadRequest },
      TContext
    >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loadLlm>>,
  TError,
  { data: LlmLoadRequest },
  TContext
> => {
  return useMutation(getLoadLlmMutationOptions(options), queryClient)
}
export const getUnloadLlmUrl = () => {
  return `/api/v1/llm`
}

export const unloadLlm = async (options?: RequestInit): Promise<LlmState> => {
  return fetchApi<LlmState>(getUnloadLlmUrl(), {
    ...options,
    method: 'DELETE',
  })
}

export const getUnloadLlmMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError, void, TContext>
  request?: SecondParameter<typeof fetchApi>
}): UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError, void, TContext> => {
  const mutationKey = ['unloadLlm']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof unloadLlm>>, void> = () => {
    return unloadLlm(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UnloadLlmMutationResult = NonNullable<Awaited<ReturnType<typeof unloadLlm>>>

export type UnloadLlmMutationError = ApiError

export const useUnloadLlm = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError, void, TContext>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof unloadLlm>>, TError, void, TContext> => {
  return useMutation(getUnloadLlmMutationOptions(options), queryClient)
}
export const getGetLlmCatalogUrl = () => {
  return `/api/v1/llm/catalog`
}

export const getLlmCatalog = async (options?: RequestInit): Promise<LlmCatalog> => {
  return fetchApi<LlmCatalog>(getGetLlmCatalogUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetLlmCatalogQueryKey = () => {
  return [`/api/v1/llm/catalog`] as const
}

export const getGetLlmCatalogQueryOptions = <
  TData = Awaited<ReturnType<typeof getLlmCatalog>>,
  TError = ApiError,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData>>
  request?: SecondParameter<typeof fetchApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetLlmCatalogQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLlmCatalog>>> = ({ signal }) =>
    getLlmCatalog({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    gcTime: 300000,
    retry: 1,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetLlmCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getLlmCatalog>>>
export type GetLlmCatalogQueryError = ApiError

export function useGetLlmCatalog<
  TData = Awaited<ReturnType<typeof getLlmCatalog>>,
  TError = ApiError,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlmCatalog>>,
          TError,
          Awaited<ReturnType<typeof getLlmCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLlmCatalog<
  TData = Awaited<ReturnType<typeof getLlmCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlmCatalog>>,
          TError,
          Awaited<ReturnType<typeof getLlmCatalog>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLlmCatalog<
  TData = Awaited<ReturnType<typeof getLlmCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetLlmCatalog<
  TData = Awaited<ReturnType<typeof getLlmCatalog>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlmCatalog>>, TError, TData>>
    request?: SecondParameter<typeof fetchApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetLlmCatalogQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
