name: Build

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install --no-install-recommends \
            libgtk-3-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: koharu-app-${{ matrix.os }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Install macOS CEF helper targets
        if: startsWith(matrix.os, 'macos')
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - run: bun install
      - run: bun run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: koharu-${{ matrix.os }}
          path: |
            target/release/koharu*
          retention-days: 3
